### ISSUE TITLE
Parsing error when converting a specific durative-action in temporal problems

### ISSUE THREAD

**Issue by AfkValerik** [aiplan4eu/unified-planning#235]
I got this error trying to convert the domain of the rovers problem, the parser doesn't recognize correctly the recharge action of the domain.

The error is shown below: 
`Traceback (most recent call last):
  File "/home/valerik/Desktop/programmazione/planning/planning-test-cases/up_conversion.py", line 11, in <module>
    pddl_problem = reader.parse_problem((path + 'rovers/rovers_domain.pddl'),(path + 'rovers/rovers_pfile2.pddl'))
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 808, in parse_problem
    self._add_timed_effects(
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 519, in _add_timed_effects
    self._add_effect(
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 413, in _add_effect
    self._parse_exp(problem, act, types_map, {}, exp[2], assignments),
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 353, in _parse_exp
    solved.append(self._em.ParameterExp(act.parameter(exp[1:])))
  File "/home/valerik/.local/lib/python3.8/site-packages/unified_planning/model/action.py", line 95, in parameter
    return self._parameters[name]
KeyError: 'duration'`

Generated by the action:
(:durative-action recharge
:parameters (?x - rover ?w - waypoint)
:duration (= ?duration (/ (- 80 (energy ?x)) (recharge-rate ?x)))
:condition (and (at start (at ?x ?w)) (over all (at ?x ?w)) 
					(at start (in_sun ?w)) (at start (<= (energy ?x) 80)))
:effect (and (at end (increase (energy ?x) (* ?duration (recharge-rate ?x)))))
)

[pddl_files.zip](https://github.com/aiplan4eu/unified-planning/files/9426413/pddl_files.zip)

**Comment by mikand** [comment]
@AfkValerik At the moment, we do not support the use of `?duration` in expressions (i.e. no duration-dependent effects).
