### ISSUE TITLE
Incorrect error message in case of using only pyperplan with optimality metric

### ISSUE THREAD

**Issue by racinmat** [aiplan4eu/unified-planning#294]
**Describe the bug**
I have defined problem where I maximize a metric. I installed this package using `pip install unified-planning[pyperplan]`

It throws error:
```
Traceback (most recent call last):
  File "C:\Projects\advent_of_code_2022\days\day_16\main.py", line 122, in <module>
    res1 = execute_part1()
  File "C:\Projects\advent_of_code_2022\days\day_16\main.py", line 104, in execute_part1
    with OneshotPlanner(problem_kind=problem.kind) as planner:
  File "C:\Users\Azathoth\.conda\envs\aoc2022\lib\site-packages\unified_planning\shortcuts.py", line 134, in OneshotPlanner
    return get_env().factory.OneshotPlanner(name=name, names=names, params=params,
  File "C:\Users\Azathoth\.conda\envs\aoc2022\lib\site-packages\unified_planning\engines\factory.py", line 210, in OneshotPlanner
    return self._get_engine('oneshot_planner', name, names, params, problem_kind, optimality_guarantee)
  File "C:\Users\Azathoth\.conda\envs\aoc2022\lib\site-packages\unified_planning\engines\factory.py", line 182, in _get_engine
    EngineClass = self._get_engine_class(engine_kind, name, problem_kind, optimality_guarantee, compilation_kind, plan_kind)
  File "C:\Users\Azathoth\.conda\envs\aoc2022\lib\site-packages\unified_planning\engines\factory.py", line 112, in _get_engine_class
    raise up.exceptions.UPNoSuitableEngineAvailableException(msg)
UnboundLocalError: local variable 'msg' referenced before assignment

Process finished with exit code 1
```
because the `msg` is defined only in single branch of 
```python
        if len(planners_features) > 0:
            header = ['Engine'] + problem_features
            if optimality_guarantee is not None:
                header.append('OPTIMALITY_GUARANTEE')
                msg = f'No available engine supports all the problem features:\n{format_table(header, planners_features)}'
```

**To Reproduce**
1. Install it using `pip install unified-planning[pyperplan]`
2. Define a problem
```python
total_points = Fluent("total_points", IntType(0))
problem = Problem("valves_problem")
problem.add_quality_metric(model.metrics.MaximizeExpressionOnFinalState(total_points))
...(other stuff)
with OneshotPlanner(problem_kind=problem.kind) as planner:
    # Asking the planner to solve the problem
    plan = planner.solve(problem)
    # Printing the plan
    print(plan)
```

**Expected behavior**
I would expect proper error message, not unassigned variable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.10

**Comment by alvalentini** [comment]
@racinmat thanks for the bug report.

In the last release, this issue should be fixed.

Can you check and, if solved, close the issue?

**Comment by racinmat** [comment]
Works now, thanks.
