### ISSUE TITLE
Using (: function) triggers a parsing error

### ISSUE THREAD

**Issue by RobertL31** [aiplan4eu/unified-planning#464]
Hello, I'm really new to PDDL, so this issue might be trivial.
I am currently trying to implement some simple problem in PDDL and use your project as a solving interface with .pddl files.

The current problem I am trying to solve is the [cannibals problem](https://en.wikipedia.org/wiki/Missionaries_and_cannibals_problem).
To be able to count how much cannibals are on each side, I would like to use a function over a shore object.

I am currently having a parsing error near the function tag.
The error:
```bash
Traceback (most recent call last):
  File "solve.py", line 11, in <module>
    problem = reader.parse_problem(domain_file, problem_file)
  File "/home/lrobert/Documents/PDDL_learning/venv/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 1638, in parse_problem
    return self.parse_problem_string(domain_str, problem_str)
  File "/home/lrobert/Documents/PDDL_learning/venv/lib/python3.8/site-packages/unified_planning/io/pddl_reader.py", line 1658, in parse_problem_string
    domain_res = parse_string(self._pp_domain, domain_str, parse_all=True)
  File "/home/lrobert/Documents/PDDL_learning/venv/lib/python3.8/site-packages/unified_planning/io/utils.py", line 25, in parse_string
    return obj.parse_string(problem_str, parse_all=parse_all)
  File "/home/lrobert/Documents/PDDL_learning/venv/lib/python3.8/site-packages/pyparsing/core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: , found '('  (at char 299), (line:19, col:1)
```

So my question is, am I doing things wrong with functions or is that some management on your side ? I saw code about it while digging, but couldn't track is so much.

Here is my PDDL and python interface:

problem.pddl:
```pddl
(define (problem problem_name) (:domain domain_name)
(:objects
    boat1 - room
    boat2 - room
    left_shore - shore
    right_shore - shore
    can1 - can
    can2 - can
    can3 - can
    ex1 - ex
    ex2 - ex
    ex3 - ex
)

(:init
    (is-can can1)
    (is-can can2)
    (is-can can3)
    (is-ex ex1)
    (is-ex ex2)
    (is-ex ex3)
    (at-person can1 left_shore)
    (at-person can2 left_shore)
    (at-person can3 left_shore)
    (at-person ex1 left_shore)
    (at-person ex2 left_shore)
    (at-person ex3 left_shore)
    (knows can1)
    (knows ex1)
    (knows ex2)
    (knows ex3)
    (at-boat left_shore)
    (free boat1)
    (free boat2)
    (= (ex_amount left_shore) 3)
    (= (can_amount left_shore) 3)
    (= (ex_amount right_shore) 0)
    (= (can_amount right_shore) 0)
)


(:goal (and
    (at-person can1 right_shore)
    (at-person can2 right_shore)
    (at-person can3 right_shore)
    (at-person ex1 right_shore)
    (at-person ex2 right_shore)
    (at-person ex3 right_shore)
))


)
```

domain.pddl
```pddl
;Header and description

(define (domain domain_name)

;remove requirements that are not needed
(:requirements :typing :fluents :conditional-effects)

(:types
    site person - object
    can ex - person
    room shore - site
)

(:functions
    (ex_amount ?s - shore)
    (can_amount ?s - shore)
)

(:predicates
    (is-can ?p - person)
    (is-ex ?p - person)
    (at-person ?p - person ?s - site)
    (at-boat ?s - shore)
    (knows ?p - person)
    (free ?r - room)
)

(:action embark
    :parameters (?p - person ?s - shore ?r - room)
    :precondition (and
        (at-boat ?s)
        (at-person ?p ?s)
        (free ?r)
        (> (ex_amount ?s) (can_amount ?s))
    )
    :effect (and 
        (not (free ?r))
        (not (at-person ?p ?s))
        (at-person ?p ?r)
        (when (is-ex ?p) (decrease (ex_amount ?s) 1))
        (when (is-can ?p) (decrease (can_amount ?s) 1))
    )
)

(:action land
    :parameters (?p - person ?s - shore ?r - room)
    :precondition (and 
        (at-boat ?s)
        (at-person ?p ?r)
        (> (ex_amount ?s) (can_amount ?s))
    )
    :effect (and 
        (free ?r)
        (not (at-person ?p ?r))
        (at-person ?p ?s)
        (when (is-ex ?p) (increase (ex_amount ?s) 1))
        (when (is-can ?p) (increase (can_amount ?s) 1))
    )
)

(:action sail
    :parameters (
        ?from - shore 
        ?to - shore
    )
    :precondition (and
        (at-boat ?from)
        (exists (?p - person) 
            (exists (?r - room) 
                (and  
                    (at-person ?p ?r)
                    (knows ?p)
                )
            )
        )
    )
    :effect (and
        (at-boat ?to)
        (not (at-boat ?from))
    )
)
)
```

python intrerface:
```python
from unified_planning.io import PDDLReader
from unified_planning.shortcuts import *
from unified_planning.engines import PlanGenerationResultStatus

folder = 'cannibals/'

domain_file = folder + 'domain.pddl'
problem_file = folder + 'problem.pddl'

reader = PDDLReader()
problem = reader.parse_problem(domain_file, problem_file)

embark = problem.actions[0]
land = problem.actions[1]
sail = problem.actions[2]
costs = {
    embark: 0,
    land: 0,
    sail: 0
}

problem.add_quality_metric(
    up.model.metrics.MinimizeActionCosts(costs)
)

with OneshotPlanner(
    problem_kind=problem.kind,
    optimality_guarantee=PlanGenerationResultStatus.SOLVED_OPTIMALLY,
) as planner:
    final_report = planner.solve(problem)
    plan = final_report.plan
    total_cost = 0
    if plan is None:
        print('no plan found')
        print(final_report)
        exit()
    for i, action in enumerate(plan.actions):
        print(f'[{i}][{total_cost}] - {action}')
        total_cost += costs[action.action]
    print("%s returned: %s" % (planner.name, plan))
```
Here is a zip for simplicity sake:
[cannibals.pddl.zip](https://github.com/aiplan4eu/unified-planning/files/12183418/cannibals.pddl.zip)

These are the modules version i used: 
```
networkx==3.1
pyparsing==3.1.0
unified-planning==1.0.0
up-fast-downward==0.2.3
```

**Comment by Framba-Luca** [comment]
Hi @RobertL31.

In the files you sent there were 3 issues:

1.  In the `PDDLReader` we assumed that `predicates` are defined before `functions`; this was causing your parsing issue.
2. After the problem got parsed, in your zip files, you were missing the `init` of the functions (but you wrote them in the expansions above) `(= (ex_amount left_shore) 3) (= (can_amount left_shore) 3) (= (ex_amount right_shore) 0) (= (can_amount right_shore) 0)`.
3. After fixing the 2 points above, the planner returned `Problem Unsolvable`; the issue here is that the `embark` and `land` actions, in the conditions, should have `>=` and not only `>`.

I added the zip file with all the corrections; those files work for me, let me know if they work for you.

[cannibals.zip](https://github.com/aiplan4eu/unified-planning/files/12184042/cannibals.zip)

In the future we might relax the first point, as we realized it's too strict, in the meantime define predicates before functions :)

Thanks for the feedback!
