### ISSUE TITLE
Parsing error.

### ISSUE THREAD

**Issue by MFaisalZaki** [aiplan4eu/unified-planning#479]
I'm trying to load the `zenotravel` from the `ipc-2002` and I get this error:
```
pyparsing.ParseException: Expected ")", found '-'  (at char 119), (line:4, col:21)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ma342/.local/lib/python3.10/site-packages/unified_planning/io/pddl_reader.py", line 1638, in parse_problem
    return self.parse_problem_string(domain_str, problem_str)
  File "/home/ma342/.local/lib/python3.10/site-packages/unified_planning/io/pddl_reader.py", line 1658, in parse_problem_string
    domain_res = parse_string(self._pp_domain, domain_str, parse_all=True)
  File "/home/ma342/.local/lib/python3.10/site-packages/unified_planning/io/utils.py", line 23, in parse_string
    return obj.parseString(problem_str, parseAll=parse_all)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4065, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Expected ")", found '-'  (at char 119), (line:4, col:21)
```
Code to reproduce:
```
from unified_planning.io import PDDLReader
PDDLReader().parse_problem('domain.pddl', 'instance-1.pddl')
```

and here are the [files.zip](https://github.com/aiplan4eu/unified-planning/files/12453295/files.zip).

**Comment by alvalentini** [comment]
The problem here is that we do not support the `either` keyword, both in the PDDL parser and in the internal problem representation.
